auto-save: 60 #interval for auto-saving in minutes.
check-update: true #automatically checks for updates. Set to false to disable.
lang: en

mount-cost: #setting of > 0 disables sale. 0 enables free give-away.
  pig: 50
  horse: 150
  donkey: 100
  mule: 100
  skeleton: 1000
  zombie: -1
  health: 5
  speed: 15
  jump: 8
  noble: 0.75
  geometricCost: "false" # NOT-ACTIVE Are health, speed, and jump multipliers instead of constants?
  tiered: "false" # NOT-ACTIVE Disregard previous 4 entries and cost by tier instead?
  t1: 120 # Point totals will automatically be distributed across the amount of tiers declared here.
  t2: 260
  t3: 296
 
stable:
  max-mounts: 27 #value of 0 = unlimited. Must be divisible by 9.
  price-init: 4
  price-per-day: 2
  min-speed: 30
  max-speed: 120
  mod-speed: 1
  min-jump: 30
  max-jump: 120
  mod-jump: 1.5

wharf:
  max-mounts: 64
  price-init: 2
  location-log: true # place vehicle where it was taken from? else throw item down
  
station:
  max-mounts: 64
  price-init: 2
  location-log: true

icons:
  pickup: "SADDLE"
  dropoff: "BED"
  pay: "GOLD_INGOT"
  purchase: "PAPER"
  exit: "WOOD_DOOR"
  settleDebt: "FEATHER"
  clearBooks: "BOOK"
  exitPay: "WOOD_DOOR"
  button: "STONE_BUTTON"
  pig: "CARROT_ITEM"
  horse: "SADDLE"
  donkey: "APPLE"
  mule: "CHEST"
  skeleton: "BONE"
  zombie: "ROTTEN_FLESH"
  health: "RED_MUSHROOM"
  jump: "FENCE_GATE"
  speed: "FEATHER"
  white: "SNOW_BLOCK"
  buckskin: "WOOD"
  chestnut: "HARD_CLAY"
  bay: "SOUL_SAND"
  black: "COAL_BLOCK"
  dapple: "STONE"
  liver: "NETHER_BRICK"
  plain: "LEATHER"
  blaze: "GHAST_TEAR"
  paint: "MILK_BUCKET"
  appaloosa: "PUMPKIN_SEEDS"
  sooty: "COAL"
  buy: "GOLD_INGOT"
  exitBuy: "WOOD_DOOR"